from constantes import *
manPage0 = ["Manuel de l'Aventure - Par Lena","**__Sommaire :__**"]

manPage1 = ["Généralités","L'Aventure consiste à la réaliser plusieurs missons réparties en plusieurs chapitres.\n\nCes missions sont scénarisés et consistes en une succession d'événements prédéfinies qui vont mettre vos statistiques à l'épreuve"]
manPage2 = ["Statistiques Principales","Les statistiques principales sont au nombre de 7 :\n\n{0} __**Force :**__ Influence la puissance des armes et compétences physiques\n\n{1} __**Endurance :**__ Influence les PV maximums, l'armure et les soins reçus, la probabilité de recevoir des soins et armures critique ainsi que, pour les aaspirations de mêlée, les dégâts infligés\n\n{2} __**Charisme :**__ Influence les soins réalisées ainsi que certaines compétences de bonus ou de malus\n\n{3} __**Agilité**__ : Influt sur les probabilités d'esquiver une attaque et sur le taux de coups critiques des compétences de dégâts\n\n{4} __**Précision**__ : Influ sur la probabilité de réussir une attaque ainsi que sur le taux de coup critique des compétences de dégâts, soins et armures\n\n{5} __**Intelligence :**__ Influance l'Armure donné, certaines compétences de bonus ou malus et accroi la probabilité d'infliger des dégâts indirects critiques tout en diminuant celle d'en recevoir\n\n{6} __**Magie :**__ Influence la puissance des armes et compétences magiques".format(statsEmojis[0],statsEmojis[1],statsEmojis[2],statsEmojis[3],statsEmojis[4],statsEmojis[5],statsEmojis[6])]
manPage3 = ["Statistiques Secondaires","Les statistiques secondaires sont au nombre de 3\nContrairement aux statistiques principales, seuls les équipements ainsi que les bonus de compétences peuvent infliger dessus\n\n{0} __**Résistance :**__ Réduit les dégâts reçus. Plus la résistance est élévée, plus les palliers pour réduire d'avantage les dégâts sont conséquants\n\n{1} __**Pénétration d'Armure :**__ Ignore une partie de la résistance adverse\n\n{2} __**Critique :**__ Chaque point augmente de **1%** votre taux de coup critique des compétences de dégâts, soins et armures".format(statsEmojis[RESISTANCE],statsEmojis[PERCING],statsEmojis[CRITICAL])]
manPage4 = ["Statistiques d'Actions","Les statistiques d'actions se rajoute ou se soustraient à vos statistiques lorsque vous réalisez l'action correspondante\nSeul les équipements peuvent influer dessus\n\n{0} __**Soins** :__ S'aditionne aux statistiques d'un combattant lorsque celui-ci soigne un allié\n{2} __**Armure et mitigation** :__ S'aditionne aux statistiques d'un combattant octroi une armure ou un effet réduisant les dé^gats indirects reçus\n{1} __**Boost et malus** :__ S'aditionne aux statistiques d'un combattant lorsque celui-ci octroi un effet augmentant ou diminuant les statistiques d'une cible\n{3} __**Dégats directs** :__ S'aditionne aux statistiques lorsqu'un combattant inflige des dégâts à l'aide d'une compétence\n{4} __**Dégâts indirects** :__ S'aditionne aux statistiques lorsqu'un combattant inflige des dégâts à l'aide d'un effet octryé au préalable par une compétence ou un passif".format(statsEmojis[ACT_HEAL_FULL],statsEmojis[ACT_BOOST_FULL],statsEmojis[ACT_SHIELD_FULL],statsEmojis[ACT_DIRECT_FULL],statsEmojis[ACT_INDIRECT_FULL])]
manPage5 = ["Présentation des combats","Une chose que vous serez souvent ammené durant votre aventure est à vous battre\n\nLors de ceux-ci, vous et toute votre équipe affronterez une équipe d'adversaire pouvant être prédéfinie ou aléatoire, suivant les missions\n\nAu début de chaque combat, un check-in sera réalisé. Les membres de votre équipe n'ayant pas réagit avant la fin du délais seront considérés comme des combattants automatiques\n\nLes combats se déroulent au tour part tour\nBien que la timeline soit une alternation entre Membre de l'Equipe 1 et Membre de l'Equipe 2, l'odre dans laquelle les personnages jouront est aléatoire, cependant plusieurs facteurs peuvent infliger dessus :\nLes combattants possédants beaucoup de compétences de boost, les combattants de mêlée ainsi que les combattants manuels ont plus de chances de commencer dans les premiers de la timeline, alors que les soigneurs et armuriers auront tendance à jouer en dernier\n\nUn combat se termine quand tous les membres d'une équipe ont été éliminés"]
manPage6 = ["L'Arme","__**En combat :**__\nChaque personnage utilise en combat l'arme qu'il a équippé\nLes armes determinent les placements au début du combat\n\nPour utilier votre arme, il faut que votre cible se trouve à portée et que vous ayez une ligne de vue dessus\n\nChaque arme tir un nombre prédéfinie de fois et possède une précision par défaut, affecté par votre **Précision** ainsi l'**Agilité** de votre cible\nSi l'attaque porte, vous lui infligez des dégâts dépendant de la statistique utilisée par votre arme.\n\nCertaines armes peuvent accorder des effets passifs, qui sont attribués au début du combat\n\n__**Obtention :**__\nVous pouvez vous procurrez des armes au **Magasin** ou les looter en fin de combat\n\n__Exemple de page d'information d'une arme :__","https://media.discordapp.net/attachments/771410084961058836/871140947155644467/Capture_decran_de_2021-07-31_23-22-28.jpg"]
manPage7 = ["Les Compétences","**__En combat :__**\nLorsque vous utilisez les compétences que vous avez équipés, divers effets peuvent se produire, décrit dans la page d'information de la compétence\n\nSi votre compétence est un compétence de **__Dégâts__**, ceux-ci sont produits instantannément en tant que dégâts directs et prennent bien souvent la **Force** ou la **Magie** comme statistiques de base. Cette information est affiché de la page d'information de la compétence, donc faites s'y attention pour éviter de vous retrouver avec des compétences magiques en ayant maxé la force\n\nL'**__Armure__** donnés par certaines compétences augmente temporairement la santé de la cible. Si des dégâts font tomber les PV de l'armure à 0, celle-ci absorbe encore quelques dégâts avant de disparaitre\nGénéralement, la puissance de l'armure est augmentée par le **__Charisme__** ou l'**__Intelligence__** du lanceur ainsi que l'**__Endurance__** de votre cible\n\nLes compétences de **__Boost__** donnent des statistiques supplémentaires aux alliés ciblés ou dans la zone d'effet.\nLes compétences de boosts sont augmentés par le **__Charisme__** ou l'**__Intelligence__** suivant la compétence\n\nLes compétences de __**Malus**__ sont simillaires aux compétences de Boost, mais donne des malus de statistiques aux adversaires\n\nLes compétences de __**Soins**__... soignent. La puissance des soins est affecté par le **__Charisme__**\n\nPour finir, les compétences de __**Dégâts Indirects**__ infligent des dégâts sous condition. Les dégâts indirects ne déclanchent pas les effets s'activant sur dégâts reçus et passe sous l'armure. Leur puissance est augmente par l'**__Intelligence__**\n\n__**Obtention :**__\nVous pouvez vous procurrez des compétences au **Magasin** ou les looter en fin de combat\nCertaines compétences peuvent être exclusives à une aspiration ou un élément particulier, d'autres appartiennent à des groupes spirituels qui s'exclus entre eux ou encore, certaine compétences peuvent octroyer des Jauges\n__Exemple de page d'information de compétence :__",'https://media.discordapp.net/attachments/771410084961058836/871139294092345344/Capture_decran_de_2021-07-31_23-15-13.png']
manPage8 = ["Vos personnages","Chaque joueur a un personnage unique qui est partagé entre tous les serveurs. Si vous n'avez pas encore le votre, vous pouvez le créer à l'aide de la commande `/start` après avoir lu ce chapitre\n\nLe personnage sera ammené à combattre mais pas seulement ! Pour cela il possède une page d'aptitudes, de compétence et d'équipement !\n\n__Les aptitudes (ou statistiques) :__\nLa base de votre personnage. Durant l'aventure, vous serez amené à gagner en niveau et vos statistiques en feront tout autant !\nMais pour qu'il y ai un peu de disparité, chaque statistique évolu différament selon votre **aspiration**.\nPtdrCKoi ? Et bah tournons la page"]

manPage9 = ["Aspiration Berskeur","Tank - Force\nLes berserkeurs sont des combattants de mêlée qui ont tout à gagner à frapper leurs ennemis.\nLeurs compétences exclusives leurs permettent de récuper des points de vie ou des points d'armures en frappant leurs adversaires\n\n__**Passif d'Aspiration :**__\nPossède naturellement {7}% de vol de vue\n\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[0][0],aspiStats[0][1],aspiStats[0][2],aspiStats[0][3],aspiStats[0][4],aspiStats[0][5],aspiStats[0][6],BERS_LIFE_STEAL)+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[0][0]], nameStats[recommandedStat[0][1]])]
manPage10 = ["Aspiration Observateur","Distance - Force\nLes observateurs préfères rester loins des combats, et c'est là qu'ils sont le plus efficace !\nLeurs compétences exclusives ont en général une très bonne précision de base\n\n__**Passif d'Aspiration :**__\nÀ chaques tirs touchés, le taux de critique des Observateurs augmente de **3%**. Le bonus est rénitialisé en cas de coup critique réalisée grâce à ce bonus et diminue de 20% à chaque attaque ratée\nLes coups critiques infligent plus de dégâts, qu'ils soient infligés avec ce passif ou non\n\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[1][0],aspiStats[1][1],aspiStats[1][2],aspiStats[1][3],aspiStats[1][4],aspiStats[1][5],aspiStats[1][6])+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[1][0]], nameStats[recommandedStat[1][1]])]
manPage11 = ["Aspiration Poids Plume","Mêlée - Force\nLes Poids Plumes aiment bien danser sous les tirs adverses, tout en portant des coups là où ça fait mal !\nLeurs compétences exclusives visent en général a frapper l'ennemi plusieurs fois pour leur donner un maximum d'occasion d'effectuer des coups critiques\n\n__**Passif d'Aspiration :**__\nPour chaque esquive réalisée, le taux de critique des Poids Plumes augmente de 3%. Le bonus est réniatilsé en cas de coup critique réalisé grace à ce bonus et est divisé par 2 en fin de tour du Poids Plume\nLes coups critiques infligent plus de dégâts\n\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[2][0],aspiStats[2][1],aspiStats[2][2],aspiStats[2][3],aspiStats[2][4],aspiStats[2][5],aspiStats[2][6])+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[2][0]], nameStats[recommandedStat[2][1]])]
manPage12 = ["Aspiration Idole","Distance - Support\nLes idoles sont de bon soutiens pour leur équipe mais compte également sur elle pour faire le reste du boulot à leur place\nLeurs compétences exclusives visent à booster leurs alliés\n\n__**Passif d'Aspiration :**__\nLa puissance boost qu'ils donnent augmente en fonction du nombre d'allié en vie\n\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[3][0],aspiStats[3][1],aspiStats[3][2],aspiStats[3][3],aspiStats[3][4],aspiStats[3][5],aspiStats[3][6])+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[3][0]], nameStats[recommandedStat[3][1]])]
manPage13 = ["Aspiration Prévoyant","Distance - Armure\nLes Prévoyants n'ont pas leur pareil pour protéger leurs coéquipiers à l'aide de leurs armures\nLeurs compétences exclusives sont généralement de très bonnes compétences d'armures\n\n__**Passif d'Aspiration :**__\nLa puissance des boucliers des Prevoyants est plus élevée au début du combat\n\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[4][0],aspiStats[4][1],aspiStats[4][2],aspiStats[4][3],aspiStats[4][4],aspiStats[4][5],aspiStats[4][6])+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[4][0]], nameStats[recommandedStat[4][1]])]
manPage14 = ["Aspiration Tête Brulée","Tank - Force\nLes Têtes Brûlées sont des rebels dans l'âme qui font pleuvoir les coups sur leurs adversaires\nLeurs compétences exclusives réduisent les Pv Maximums de leurs cibles\n\n__**Passif d'Aspiration :**__\nÀ chaque attaque effectuée, diminue les PVs maximums des cibles de l'équivalent de **35%** des dégâts infligés\n\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[5][0],aspiStats[5][1],aspiStats[5][2],aspiStats[5][3],aspiStats[5][4],aspiStats[5][5],aspiStats[5][6])+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[5][0]], nameStats[recommandedStat[5][1]])]
manPage15 = ["Aspiration Mage","Distance - Magie\nLes mages ont préféré délaisser les armes conventionnelles pour s'attarder sur une autre source de dégâts : La magie\nLeurs compétences exclusives sont en général de puissantes compétences magiques\n\n__**Passif d'Aspiration :**__\nLa puissance des compétences ultimes de dégâts est augmenté de 20%\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[6][0],aspiStats[6][1],aspiStats[6][2],aspiStats[6][3],aspiStats[6][4],aspiStats[6][5],aspiStats[6][6])+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[6][0]], nameStats[recommandedStat[6][1]])]
manPage16 = ["Aspiration Altruiste","Distance - Soins\nLes altruistes vont préférer se focaliser sur leurs alliés plutôt que sur eux-même\nLeurs compétences exclusives en font de très bons soigneurs\n\n__**Passif d'Aspiration :**__\nLa puissance des soins donnés à leurs alliés est augmentée, mais ceux réalisé sur soi-même est diminuée\n\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[7][0],aspiStats[7][1],aspiStats[7][2],aspiStats[7][3],aspiStats[7][4],aspiStats[7][5],aspiStats[7][6])+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[7][0]], nameStats[recommandedStat[7][1]])]
manPage18 = ["Aspiration Enchanteur","Tank - Magie\nLes Enchanteurs veulent démontrer que la Magie n'est pas uniquement réservée à ceux qui restent bien au chaud à l'arrière\nLeurs compétences exclusives leurs permettent d'infliger des dégâts magiques tout en prolongeant leur temps passé dans la mêlée\n\n__**Passif d'Aspiration :**__\nÀ chaque attaque subie, la Magie augmente de 5% (1 fois par ennemi et par tour)\nLe bonus est rénitialisé en fin de tour\n\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[8][0],aspiStats[8][1],aspiStats[8][2],aspiStats[8][3],aspiStats[8][4],aspiStats[8][5],aspiStats[8][6])+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[8][0]], nameStats[recommandedStat[8][1]])]
manPage19 = ["Aspiration Protecteur","Tank - Armure\nLes protecteurs protègent leur équipe en se mettant face à l'ennemi\nLeurs compétences exclusives permettent d'octroyer des armures aux alliés sans se délaisser pour autant\n\n__**Passif d'Aspiration :**__\nÀ chaque attaque subie, augmente de 5% les armures données (1 fois par ennemi et par tour)\nLe bonus est rénitialisé en fin de tour\n\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[9][0],aspiStats[9][1],aspiStats[9][2],aspiStats[9][3],aspiStats[9][4],aspiStats[9][5],aspiStats[9][6])+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[9][0]], nameStats[recommandedStat[9][1]])]
manPage25 = ["Aspiration Vigilant","Tank - Soins\nLes Vigilants gardent toujours un oeuil à la fois sur leurs alliés comme sur leurs ennemis.\nLeurs compétences exclusives leurs permettent de soigner leurs alliés tout en se maintenant haut en PV également\n\n__**Passif d'Aspiration :**__\nÀ chaque attaque subie, augmente de 5% les soins réalisées (1 fois par ennemi et par tour)\nLe bonus est rénitialisé en fin de tour\n\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[10][0],aspiStats[10][1],aspiStats[10][2],aspiStats[10][3],aspiStats[10][4],aspiStats[10][5],aspiStats[10][6])+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[10][0]], nameStats[recommandedStat[10][1]])]
manPage26 = ["Aspiration Sorcier","Distance - Magie\nLes Sorciers ont décidés que rien n'était plus satisfaisant que de voir leurs ennemis mourir à petit feu\nLeurs compétences exclusives infligent des dégâts indirects pendant un bon moment\n\n__**Passif d'Aspiration :**__\nÀ chaque élimination réalisée, inflige des dégâts magiques indirect au corps à corps de la cible d'une puissance équivalent à **50%** du niveau\n\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[11][0],aspiStats[11][1],aspiStats[11][2],aspiStats[11][3],aspiStats[11][4],aspiStats[11][5],aspiStats[11][6])+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[11][0]], nameStats[recommandedStat[11][1]])]
manPage27 = ["Aspiration Inovateur","Distance - Support\nLes Innovateurs ne manquent pas d'ingéniosité piur se surpasser en combat\nLeurs compétences exclusives visent à augmenter les dégâts infligés par les alliés\n\n__**Passif d'Aspiration :**__\nLa puissance boost qu'ils donnent augmente en fonction du nombre d'ennemis en vie\n\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[12][0],aspiStats[12][1],aspiStats[12][2],aspiStats[12][3],aspiStats[12][4],aspiStats[12][5],aspiStats[12][6])+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[12][0]], nameStats[recommandedStat[12][1]])]
manPage28 = ["Aspiration Attentif","Distance - Force\nLes Attentifs préfèrent attendre le moment opportin pour frapper là où ça fera le plus mal tout en entravant les soins de leurs cibles\nLeurs compétences exclusives inligent des dégâts indirects sur une longue durée\n\n__**Passif d'Aspiration :**__\nLes effets de dégâts indirects infligés par un Attentif ont pour effet secondaire de réduire les sois reçu par leurs cibles\n\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[13][0],aspiStats[13][1],aspiStats[13][2],aspiStats[13][3],aspiStats[13][4],aspiStats[13][5],aspiStats[13][6])+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[13][0]], nameStats[recommandedStat[13][1]])]
manPage33 = ["Aspiration Mascotte","Tank - Boost\nLes mascottes préfèrent voir leurs ennemis en face tout en caputalisant sur la sympatie de leurs alliés\nLeurs compétences exclusives visent à rediriger les dégâts sur eux ou infliger des malus aux ennemis\n\n__**Passif d'Aspiration**__\nEn début de tour, augmente les dégâts infligés par les alliés à 4 cases ou moins de la Mascotte en fonciton du nombre d'ennemis l'ayant attaqué depuis son dernier tour.\n{9}% du niveau par ennemi (minimum {8}%), maximum {7}\n\n__**Stats de base au niveau 50 :**__\nForce : {0}\nEndurance : {1}\nCharisme : {2}\nAgilité : {3}\nPrécision : {4}\nIntelligence : {5}\nMagie : {6}".format(aspiStats[14][0],aspiStats[14][1],aspiStats[14][2],aspiStats[14][3],aspiStats[14][4],aspiStats[14][5],aspiStats[14][6],MASC_MAX_BOOST,MASC_MIN_BOOST,MASC_LVL_CONVERT)+"\n\n__Statistiques recommandées :__\n{0}, {1}".format(nameStats[recommandedStat[14][0]], nameStats[recommandedStat[14][1]])]

manPage20 = ["Combats pour les nuls","Reçamment, vous avez vu les bases des combats, mais avant de vous lancer tête baissée dans la mêlée, il y a certaines choses que vous devez voir, histoire de ne pas être totalement déboussolées"]
manPage21 = ["Résistance Soins, Friabilité, Résurrection récente et Mort Subite","Ce sont les noms de quatres mécaniques que vous risquez de souvent buter contre, même sans vous en rendre compte\n\n__Résistance Soins__ :\nChaques soins que vous recevez augmentera petit à petit votre Résistance Soins, qui réduit la puissance des prochains effets curatifs que vous receverez.\nCette dernière augmente en fonction de vos PV maximum. Par consquéquent, plus vous avez de PV, moins la Résistance Soins viendra vous embêter. Cepedant, la présence de plusieurs combattants possédant beaucoup de compétences de soins dans une même équipe fait progresser la Résistance Soins plus rapidement\nCertains soins fixes (comme les vols de vie) ignorent la Résistance Soins.\n\n__Friabilité :__\nÀ partir d'un moment, la valeur des armures reçus va commencer à diminuer jusuq'à atteindre une valeur quasi nulle. Le seul moyen d'y échapper est de terminer le combat avant que cette mécanique ai trop d'effet\n\n__Résurection Récente :__\nChaque Résurection donne en plus une **Armure Absolue** de **20%** des PV maxmimum du revenant.\nLes armures absolues ne sont pas affectés par le malus d'armures consécutives ou les multiplicateurs de dégâts sur armure.\n\n__Mort Subite :__\nÀ partir du **Tour 21**, tous les combattants encore en vie perdent une partie de leurs PV, calculés en fonction de leurs PV maximums respectifs\nChaques tours passés en Mort Subite entraînent des dégâts de plus en plus conséquent."]
manPage22 = ["Alliés Temporaires (ou \"Temp's\")","Si votre équipe comporte moins de **8 joueurs** lors du lancement d'un combat, cette dernière sera comblée avec des PNJ nommés les \"Alliés Temporaires\" (ou \"Temp's\" pour faire plus cours)\nLeur liste peut être visualisée dans l'encyclopédie\nLes alliés temporaires s'adaptent au niveau de l'équipe qu'ils rejoignent, ainsi qu'aux roles vacants.\n\nVous pouvez également affronter une équipe composée de Temp's durant vos combats. Cette probabilité augmente en fonciton de votre nombre de victoires récentes.\n\nCertains Temp's ont une probabilitée d'être remplacés par d'autre Temp's similaires (nommés \"Variants\"), et d'autres sont exclusifs à quelques combats spéciaux"]
manPage23 = ["Combats spéciaux","Chaques combats a une probabilité de déclancher un événement spécial.\n__Combat de boss \"All vs One\" :__\nDurant ces combats, vous affronterez un ennemi unique, possédant souvent ses propres mécaniques.\nLes statistiques de ces ennemis sont diminués contre les petites équipes\n\n__Combats de boss :__\nUn ennemi notable a une chance de se glisser dans l'équipe adverse. À vous de l'éliminer avant que l'inverse se produise\n\n__Combat de raid :__\nVous êtes associé à une autre équipe (de joueur ou de Temp's) afin d'affronter un ennemi redoutable. Ces combats se déroulent sur des cartes plus grandes qu'à l'accoutumé.\n\n__Combat par procurration :__\nDurant ces combats, vous incarnez un Temp particulier le temps d'un combat"]
manPage24 = ["Taux de danger","Selon les récentes performances de votre équipe, vous pourrez être affectés à des ennemis plus ou moins puissants, et ce grâce au **Taux de Danger**\n\nCe dernier influ sur les PV maximum, les dégâts, les soins, les armures ainsi que sur l'Agilité, la Précision et la Résistance de vos ennemis.\nUn taux de victoire récentes élevée vous permettra d'affronter des équipes au taux de Danger élevé, et à contrario, trop de défaite vous fera affronter des ennemis plus faibles.\n\nLe taux de danger influ très légèrement sur l'expérience gagné en fin de combat"]
manPage29 = ["Transcendance","Si votre combat remplie plusieurs critère, vous et votre équipe aurez accès à une puissante compétence dont l'effet diffère suivant plusieurs facteurs. Utilisez la commande `/inventory nom:Transcendance` pour avoir plus d'informations à ce sujet"]
manPage30 = ['Eléments',"Une fois un certain niveau atteint, vous aurez accès aux éléments principaux et secondaires.\nLes éléments principaux sont répartis en deux catégories :\n - Le *quatuor élémentaire*, qui est débloqué en premier, augmentent vos statistiques et vos dégâts infligés lorsque vous effectuez des dégâts en remplissants certains critères propres à chacuns d'entre eux. Leurs compétences exclusives respectent pour la plupart ses critères\n - Le *quatuor dimensionnel*, débloqué plus tard, vise principalement a augmenter les atouts des supports ou des dégâts indirects, et leurs compétences exclusives vont dans ce sens\n\nLes éléments secondaires sont cumulables avec les éléments principaux, cependant ceux-ci s'accompagnent systématiquement d'un bonus et d'un malus qu'il faut prendre en compte.\n\nIl est possible de voir la liste des éléments et leurs effets avec `/inventory destination:Elements`"]
manPage31 = ['Evolution des équipements',"Plus vous monterez de niveau, plus vous remarquerez que les équipements à votre disposition octroient un nombre plus important de statistiques mais en retirent de plus en plus également, devenant de plus en plus spécialisés. Il est important de les sélectionner de sorte à ce qu'ils ne rentrent pas en contradiction entre eux, ou bien avec vos compétences"]
manPage32 = ['Prestige',"Une fois le niveau MAXLEVEL atteint, vous aurez l'occasion de Prestige votre personnage. Si tel est votre choix, vous retournerez au niveau 1, cependant vous concerverez votre inventaire et obtiendrez un *Point majeur* à répartir avec la commande `/points` comme les points d'aptitudes normaux.\nCes points majeurs octroient un grand bonus de statistiques et peuvent même être attribué dans des catégories non accéssibles avec des points normaux\n\nLes combattants venant de prestige voient leur expérience augmenter jusqu'au niveau 30, cependant plus votre équipe a un niveau de prestige élevé, plus le taux de Danger de vos combats sera augmenté également"]
manPage34 = ["Briser ses limites","Une fois le niveau 40 atteint, vous débloquerez la possibilité de briser vos limites.\nCela consiste en **un set** de bonus de statistiques composé de deux partie : **les statistiques** d'une part et sa **puissance** de l'autre.\n\nLes statistiques impactés peuvent aller jusqu'à 4 satistiques différentes définies aléatoirement, la puissance quand à elle est définie aléatoirement dans une fourchette qui dépend du nombre de statistiques présents dans le set. Moins le nombre de statistiques est élevé, plus la puissance sera grande\n\nVous pouvez dépenser des <:coins:862425847523704832> pièces pour obtenir un nouveau **set** défini aléatoirement, set que vous pouvez choisir de **conserver** ou de **passer**.\nSi vous conservez votre nouveau set, l'ancien sera __remplacé__ et __perdu__. Dans le cas ou vous préférez passer, aucun changement n'est effectuer.\n\nQue vous conserviez ou passez, les <:coins:862425847523704832> pièces utilisés ne sont pas remboursables"]

manPage34[1] += "\n\n__Fourchettes de puissance en fonction du nombre de statistiques :__"
for cmpt in range(len(tablRangeLB)):
    manPage34[1] += "\n__{0} statistique{1}__ : {2}% → {3}%".format(cmpt+1,["","s"][cmpt>0],tablRangeLB[cmpt][0],tablRangeLB[cmpt][-1])

manPage35 = ["Bonus de personnage à jour","Vous obtenez une bonus de **5%** dans toutes vos statistiques principales sur votre personnage est considéré comme étant \"à jour\".\n\nCela consiste en :\n- Avoir moins de **5 points bonus** à attribuer\n- Avoir des équipements dont le niveau est égale ou inférieur à maximum **10 niveaux** au votre\n- Avoir **aucun** emplacement de compétence vide, à l'exception du **dernier** si vous l'avez débloqué il y a **5 niveaux ou moins**"]

tablPage = [
    manPage0,manPage1,manPage2,manPage3,manPage4,manPage5,manPage6,manPage7,manPage8,manPage9,manPage10,manPage11,manPage12,manPage13,manPage14,manPage15,manPage16,manPage18,manPage19,manPage25,manPage26,manPage27,manPage28,manPage20,manPage21,manPage22,manPage23,manPage24,manPage29,manPage30,manPage31,manPage32,manPage33,manPage34,manPage35]
chapter = [
    [manPage0],
    [manPage1,manPage2,manPage3,manPage4,manPage5,manPage6,manPage7],
    [manPage8,manPage9,manPage10,manPage11,manPage12,manPage13,manPage14,manPage15,manPage16,manPage18,manPage19,manPage25,manPage26,manPage27,manPage28,manPage33],
    [manPage20,manPage21,manPage22,manPage23,manPage24,manPage29],
    [manPage30,manPage31,manPage32,manPage34,manPage35]
]

chapterName = [None,"Combat B.A.BA","Les personnages","Combat : Les subtilités","Personnage : Progression"]
lenChapter, cmptChap = [0], 0
for chap in chapter:
    lenChapter.append(len(chap)+cmptChap)
    cmptChap = len(chap)+cmptChap

for a in range(1,len(chapter)):
    manPage0[1] += f"\n**__Chapitre {a}__: {chapterName[a]}**\n\n"
    for b in range(0,len(chapter[a])):
        manPage0[1] += f"{lenChapter[a]+b} - {chapter[a][b][0]}\n"

for cmpt in range(1,len(chapter[2])):
    chapter[2][cmpt][0] = chapter[2][cmpt][0] + " "+ aspiEmoji[cmpt-1]

for cmpt in range(1,len(tablPage)):
    if cmpt != 24:
        for cmpt2 in range(len(allStatsNames)):
            if allStatsNames[cmpt2] in tablPage[cmpt][1] and not(statsEmojis[cmpt2] in tablPage[cmpt][1]):
                tablPage[cmpt][1] = tablPage[cmpt][1].replace(allStatsNames[cmpt2],"{0} {1}".format(statsEmojis[cmpt2], allStatsNames[cmpt2]))
