descSettings = "⚠ Cette commande nécessite que l'utilisateur ai la permission de gérer les salons.\n\nPermet d'initialiser le menu des paramètres du serveur.\nDe là, vous pourrez modifier le préfixe du bot, définir le salon Patchnote ou le salon Bot et activer/désactiver les couleurs automatiques."
descChoose = "Permet de choisir aléatoirement parmit plusieurs options données.\n\nl!choose *Option 1*| *Option 2* | *...* | *Option n*"
descInvite = "Renvoie un lien d'invitation pour inviter Lenapy sur un serveur.\n\n⚠ Vous devez avoir la permission de gérer le serveur en question"
descStart = "Si vous n'avez pas commencé l'aventure, permet d'initialiser le menu de départ\nVous sera demandé de choisir l'espèce, le nom, la couleur et l'aspiration de votre personnage.\n\n- Une fois choisi, il vous sera impossible de changer le nom et l'espèce de votre personnage (Privilège administrateur)\n- La couleur sera affiché sur tous les embeds en rapport avec votre personnage. Si l'option Couleur Automatique est activée sur le serveur, vous receverez un role correspodant.\n- L'aspiration détermine les statistiques de base de votre personnage et leur augmentation"
descStats = "Vous permet de voir les statistiques de votre personnage, ainsi que votre équipement."
descSolde = "Vous permet de voir la solde actuelle de votre personnage."
descInventory = "Vous permet de voir les armes et compétences dans votre inventaire.\n\nEntrez \"inventory (id)\" ou \"inventory (Nom de l'arme)\" pour avoir plus d'information sur une arme ou compétence. Si vous la possédez, vous permettra de l'équiper."
descPoints = "Vous permet de répartir vos points bonus obtenu grace aux montées de niveau"
descShop = "Vous permet de dépenser vos pièces pour acheter Armes, Compétences ou Equipement"
descTeam = "Vous permet de vous grouper avec d'autre joueurs\n\nl!team : Permet de vérifier les joueurs de votre équipe\nl!team up @mention : Permet de grouper un joueur, avec son concentemant\nl!team quit : Vous permet de quitter votre équipe"
descFight = "Vous permet de lancer un combat contre une équipe de PNJ aléatoire\nSi votre équipe comporte moins de 3 joueurs, des PNJ y seront rajoutés temporairement\n\nCette commande a 1 heure de cooldown par équipe"
descQuickFight = "Même chose que l!fight, mais affiche directement l'écran de fin\n\nCooldown : 3 heures par équipe"
descOctogone = "Lance un combat 1v1 contre l'utilisteur mentionné. Les combats PVP ne rapportent pas d'exp"
descTeamFight = "Lance un combat en équipe contre l'utilisteur mentionné. Les combats PVP ne rapportent pas d'exp"
descProcu = "Permet à un autre utilisateur d'avoir accès à votre inventaire pour équiper des trucs à votre place"

manPage0 = ["Manuel de l'Aventure - Par Lena","**__Sommaire :__**"]

manPage1 = ["Généralités","L'Avanture consiste à la réaliser plusieurs missons réparties en plusieurs chapitres.\n\nCes missions sont scénarisés et consistes en une succession d'événements prédéfinies qui vont mettre vos statistiques à l'épreuve"]
manPage2 = ["Statistiques Principales","Les statistiques principales sont au nombre de 6 :\n\n__**Force :**__ Chaque point augmente de **1%** les dégâts infligés\n\n__**Endurance :**__ Chaque point augmente de **1%** les PV max au début du combat, ainsi que les bonus d'armure reçu\n\n__**Charisme :**__ Chaque point augmente de **1%** les bonus ou malus des compétences prenant en compte cette caractéristique\n\n__**Agilité**__ et __**Précision**__ : Définnissent le taux de réussite de l'attaque ainsi que le taux de coup critique\nAgilité > Précision ennemi +100 = Précision de l'arme ennemi / 2\nPrécison > Agilité ennemi +100 = Précision de l'arme * 2\nPour chaque 6,6 points dans ces deux catégories : Taux critque **+1%**\n\n__**Intelligence :**__ Chaque point augmente de **1%** les bonus ou malus des compétences prenant en compte cette caractéristique"]
manPage3 = ["Statistiques Secondaires","Les statistiques secondaires sont au nombre de 3\nContrairement aux statistiques principales, seuls les équipement peuvent infliger dessus\n\n__**Résistance :**__ Chaque point réduit de **1%** les dégâts reçu. La réduction est cappé à 95%\n\n__**Pénétration d'Armure :**__ Contre-balance la résistance de l'adversaire. Si la pénétration est supérieur à la résistance adverse, augmente vos dégâts\n\n__**Critique :**__ Chaque point augmente de **1%** votre taux de coup critiquee"]
manPage4 = ["Présentation des combats","Une chose que vous serez souvent ammené durant votre aventure est à vous battre\n\nLors de ceux-ci, vous et toute votre équipe affronterez une équipe d'adversaire pouvant être prédéfinie ou aléatoire, suivant les missions\n\nAu début de chaque combat, un check-in sera réalisé. Les membres de votre équipe n'ayant pas réagit avant la fin du délais seront considérés comme des combattants automatiques\n\nLes combats se déroulent au tour part tour\nBien que la timeline soit une alternation entre Membre de l'Equipe 1 et Membre de l'Equipe 2, l'odre dans laquelle les personnages jouront est aléatoire\n\nUn combat se termine quand tous les membres d'une équipe ont été éliminés"]
manPage5 = ["L'Arme","__**En combat :**__\nChaque personnage utilise en combat l'arme qu'il a équippé\nLes armes determinent les placements au début du combat\n\nPour utilier votre arme, il faut que votre cible se trouve à portée et que vous ayez une ligne de vue dessus\n\nChaque arme tir un nombre prédéfinie de fois et possède une précision par défaut, affecté par la **Précision** et l'**Agilité** de votre cible\nSi l'attaque porte, vous lui infligez des dégâts dépendant de votre **Force** entre-autres\n\nChaque tir peut réaliser un **Coup Critque** qui augmente ses dégâts de 35%. Le taux de coup critique est définie par les statistiques\n\nCertaines armes peuvent accorder des effets passifs, qui sont attribués au début du combat\n\n__**Obtention :**__\nVous pouvez vous procurrez des armes au **Magasin** ou les looter en fin de combat\n\n__Exemple de page d'information d'une arme :__","https://media.discordapp.net/attachments/771410084961058836/871140947155644467/Capture_decran_de_2021-07-31_23-22-28.jpg"]
manPage6 = ["Les Compétences","**__En combat :__**\nLorsque vous utilisez les compétences que vous avez équipés, divers effets peuvent se produire, décrit dans la page d'information du sort\n\nSi votre sort est un sort de **__Dégâts__**, ceux-ci sont produits instantannément en tant que dégâts directs et prennent bien souvent la **Force** comme statistiques de base\n\nL'**__Armure__** donnés par certaines compétences augmente temporairement la santé de la cible. Si des dégâts font tomber les PV de l'armure à 0, celle-ci absorbe encore 50 dégâts avant de disparaitre\nGénéralement, la puissance de l'armure est augmentée par le **__Charisme__** ou l'**__Intelligence__** du lanceur ainsi que l'**__Endurance__** de votre cible\n\nLes compétences de **__Boost__** donnent des statistiques supplémentaires aux alliés ciblés ou dans la zone d'effet. Cepandant, la plupart de ces effets disparaissent au début de votre prochain tour\nLes compétences de boosts sont augmentés par le **__Charisme__** ou l'**__Intelligence__** suivant la compétence\n\nLes compétences de __**Debuff**__ sont simillaires aux compétences de Boost, mais donne des malus de statistiques aux adversaires\n\nLes compétences de __**Soins**__... soignent. La puissance des soins est affecté par le **__Charisme__**\n\nPour finir, les compétences de __**Dégâts Indirects**__ infligent des dégâts sous condition. Les dégâts indirects ne déclanchent pas les effets s'activant sur dégâts reçus et passe sous l'armure. Leur puissance est augmente par l'**__Intelligence__**\n\n__**Obtention :**__\nVous pouvez vous procurrez des compétences au **Magasin** ou les looter en fin de combat\n\n__Exemple de page d'information de compétence :__",'https://media.discordapp.net/attachments/771410084961058836/871139294092345344/Capture_decran_de_2021-07-31_23-15-13.png']
manPage7 = ["Vos personnages","Chaque joueur a un personnage unique qui est partagé entre tous les serveurs. Si vous n'avez pas encore le votre, vous pouvez le créer à l'aide de la commande l!start après avoir lu ce chapitre\n\nLe personnage sera ammené à combattre mais pas seulement ! Pour cela il possède une page d'aptitudes, de compétence et d'équipement !\n\n__Les aptitudes (ou statistiques) :__\nLa base de votre personnage. Durant l'aventure, vous serez amené à gagner en niveau et vos statistiques en feront tout autant !\nMais pour qu'il y ai un peu de disparité, chaque statistique évolu différament selon votre **aspiration**.\nPtdrCKoi ? Et bah tournons la page"]

manPage8 = ["Aspiration Berskeur","Les berserkeurs ne font pas dans la finess ! Plus à l'aide à la ligne de front, ils frappent les ennemis sans répis avec leurs armes et utilise peu leurs compétences, si celles-ci ne tapent pas instantanément.\n\n__**Passif d'Aspiration :**__\nPlus leurs PV sont bas, plus leurs attaquent font mal\n\n__**Stats de base au niveau 50 :**__\nForce : 50\nEndurance : 60\nCharisme : 30\nAgilité : 15\nPrécision : 20\nIntelligence : 5"]
manPage9 = ["Aspiration Observateur","Les observateurs préfères rester loins des combats, et c'est là qu'ils sont le plus efficace !\n\n__**Passif d'Aspiration :**__\nLes dégâts infligés à l'arme sur une cible à portée maximale sont augmentés\n\n__**Stats de base au niveau 50 :**__\nForce : 40\nEndurance : 20\nCharisme : 25\nAgilité : 25\nPrécision : 35\nIntelligence : 35"]
manPage10 = ["Aspiration Poids Plume","Les Poids Plumes aiment bien danser sous les tirs adverses, tout en portant des coups là où ça fait mal !\n\n__**Passif d'Aspiration :**__\nPour chaque esquive réalisée, le taux de critique des Poids Plumes augmente de 5%. Le bonus est réniatilsé en cas de coup critique réalisé grace à ce bonus et est divisé par 2 en fin de tour du Poids Plume\n\n__**Stats de base au niveau 50 :**__\nForce : 10\nEndurance : 15\nCharisme : 25\nAgilité : 65\nPrécision : 35\nIntelligence : 30"]
manPage11 = ["Aspiration Idole","Les idoles sont de bon soutiens pour leur équipe mais compte également sur elle pour faire le reste du boulot à leur place\n\n__**Passif d'Aspiration :**__\nLa puissance boost qu'ils donnent augmente en fonction du nombre d'allié\n\n__**Stats de base au niveau 50 :**__\nForce : 15\nEndurance : 15\nCharisme : 65\nAgilité : 25\nPrécision : 30\nIntelligence : 30"]
manPage12 = ["Aspiration Erudit","Les erudits sont de bon entraveur, tirant leur puissance des debuffs et des dégâts indirects qu'ils infligent aux ennemis. Mais ils peuvent toujours donner un coup de main à leur équipe, s'il le faut\n\n__**Passif d'Aspiration :**__\nL'influence de l'Intelligence lors de dégâts indirects de la part d'un erudit est plus élevée\n\n__**Stats de base au niveau 50 :**__\nForce : 25\nEndurance : 30\nCharisme : 20\nAgilité : 30\nPrécision : 35\nIntelligence : 50"]
manPage13 = ["Aspiration Tête Brulée","Les têtes brulées ont plus tendance à s'entêter et prennent leur pied en première ligne pour montrer aux ennemis qui est le plus fort. Mais leurs statistiques plutôt équilibrés leur confère une bonne versabilité\n\n__**Passif d'Aspiration :**__\nLes bonus de Force et d'Endurance (Equipement inclu) sont augmenté, mais à contratio, les malus d'Agilités et de Précision se font plus ressentir\n\n__**Stats de base au niveau 50 :**__\nForce : 35\nEndurance : 35\nCharisme : 25\nAgilité : 30\nPrécision : 35\nIntelligence : 20"]
manPage14 = ["Aspiration Altruiste","Les altruistes vont préférer se focaliser sur leurs alliés plutôt que sur eux-même\n\n__**Passif d'Aspiration :**__\nLa puissance des boosts et soins donnés à leurs alliés est augmentée, mais ceux réalisé sur soi-même est diminuée\n\n__**Stats de base au niveau 50 :**__\nForce : 15\nEndurance : 35\nCharisme : 40\nAgilité : 35\nPrécision : 20\nIntelligence : 35"]
manPage15 = ["Aspiration Aventurier","Les aventuriers n'ont pas vraiment envie de se spécialiser et font ce qu'il leur plait pour s'adapter à toutes situations\n\n__**Passif d'Aspiration :**__\nLorsqu'un aventurier réalise une action, il gagne 5 de statistique dans les statistiques non utilisés par cette action parmis la Force, le Charisme ou l'Intelligence pour le tour suivant\n\n__**Stats de base au niveau 50 :**__\nForce : 30\nEndurance : 30\nCharisme : 30\nAgilité : 30\nPrécision : 30\nIntelligence : 30"]

tablDescMod = [descSettings]
tablDescUt = [descChoose,descInvite]
tablDescAdv = [descStart,descStats,descSolde,descInventory,descPoints,descShop,descTeam,descFight,descQuickFight,descOctogone,descTeamFight,descProcu]
tablPage = [manPage0,manPage1,manPage2,manPage3,manPage4,manPage5,manPage6,manPage7,manPage8,manPage9,manPage10,manPage11,manPage12,manPage13,manPage14,manPage15]
chapter = [[manPage0],[manPage1,manPage2,manPage3,manPage4,manPage5,manPage6],[manPage7,manPage8,manPage9,manPage10,manPage11,manPage12,manPage13,manPage14,manPage15]]
chapterName = [None,"Combat B.A.BA","Les personnages"]
lenChapter = [0,1,7]

for a in range(1,len(chapter)):
    manPage0[1] += f"\n**__Chapitre {a}__: {chapterName[a]}**\n\n"
    for b in range(0,len(chapter[a])):
        manPage0[1] += f"{lenChapter[a]+b} - {chapter[a][b][0]}\n"
