from advObjects.npcSkills.npcSkills_ennemi import *

ailillPassive = skill("Acharnement","ailillPassiv",TYPE_PASSIVE,emoji=deepWound.emoji[0][0],effects=ailillPassiveEff,description="**{0}%** des dégâts directs infligés par Aillil sont en plus infligés en tant que {1} {2}".format(ailillPassiveEff.power, ailillPassiveEff.callOnTrigger.emoji[0][0], ailillPassiveEff.callOnTrigger.name))

ailillEffBleeding = copy.deepcopy(bleeding)
ailillEffBleeding.power, ailillEffBleeding.lifeSteal = 50, 50
ailillWeapEff2 = copy.deepcopy(vampirismeEff)
ailillWeapEff2.power, ailillWeapEff2.turnInit = 50, -1
ailillWeap = weapon("Tronçonneuse Sanglante","aillilWeap",RANGE_MELEE,AREA_CIRCLE_1,power=300,accuracy=200,strength=50,precision=25,percing=10,resistance=10,agility=20,damageOnArmor=1.5,emoji='<:chainsaw:1189299410794979479>',effects=ailillWeapEff2,effectOnUse=ailillEffBleeding,priority=WEAPON_PRIORITY_LOWEST)
ailillSkill4 = copy.deepcopy(obsiArcane)
ailillSkill4.effects, ailillSkill4.effectOnSelf, ailillSkill4.replay = [effect("Arcane Obsidienne","arcObsAilill",STRENGTH,power=75,area=AREA_DONUT_2,trigger=TRIGGER_INSTANT,type=TYPE_DAMAGE,emoji=ailillSkill4.emoji),ailillSkill4.effectOnSelf.callOnTrigger], None, True
ailillSkill4.effects[1].use = ailillSkill4.use = STRENGTH
ailillSkill5 = skill("Lames Dansantes","ailillSkill5",TYPE_DAMAGE,power=200,range=AREA_RANDOMENNEMI_3,area=AREA_LINE_5,cooldown=5,lifeSteal=20,description="Ailill apparait à côté d'un ennemi et inflige des dégâts sur toute une ligne dans la direction de ce dernier",emoji='<:ailillSkill3:1044636776616177734>')
ailillSkill6Eff = effect("Frappe Déphasée","ailillDephaStrikes", stat=STRENGTH,power=220,area=AREA_CIRCLE_1,lifeSteal=50,trigger=TRIGGER_ON_REMOVE,type=TYPE_DAMAGE,effPrio=1,emoji='<:ailillDephaStrikeRep:1044639469921378334>')
ailillSkill6 = skill("Frappe Déphasée","alillSkill6",TYPE_INDIRECT_DAMAGE,effects=ailillSkill6Eff,range=AREA_RANDOMENNEMI_3,area=AREA_RANDOMENNEMI_5,cooldown=5,description="Ailill marque 5 ennemis aléatoirement et viendra infliger des dé^gats autour d'eux à son prochain tour",emoji='<:ailillDephaStrike:1044639442335449113>')
ailillSkill2_4 = skill("Attaques Successives","ailillSkill2",TYPE_DAMAGE,power=400,area=AREA_CIRCLE_1,tpCac=True,range=AREA_CIRCLE_3,cooldown=6,description="Ailill effectue de multiples attaques aux airs d'effets variés sur l'ennemi ciblé",say="MAIS CREVE ENFIN !")
ailillSkill2_4_cast = effect("Cast - Attaques Successives","ailillSkill2Cast4",silent=True,replique=ailillSkill2_4)
ailillSkill2_3 = copy.deepcopy(ailillSkill2_4)
ailillSkill2_3.power, ailillSkill2_3.effectOnSelf, ailillSkill2_3.say, ailillSkill2_3.area, ailillSkill2_3.replay = 300, ailillSkill2_4_cast, "", AREA_INLINE_2, True
ailillSkill2_3_cast = effect("Cast - Attaques Successives","ailillSkill2Cast3",silent=True,replique=ailillSkill2_3)
ailillSkill2_2 = copy.deepcopy(ailillSkill2_3)
ailillSkill2_2.power, ailillSkill2_2.effectOnSelf, ailillSkill2_2.area = 200, ailillSkill2_3_cast, AREA_LINE_3
ailillSkill2_2_cast = effect("Cast - Attaques Successives","ailillSkill2Cast2",silent=True,replique=ailillSkill2_2,turnInit=2)
ailillSkill2 = copy.deepcopy(ailillSkill2_2)
ailillSkill2.power, ailillSkill2.effectOnSelf, ailillSkill2.area, ailillSkill2.tpCac, ailillSkill2.replay = 0, ailillSkill2_2_cast, AREA_MONO, False, False
ailillSkill3Eff = effect("Double Tranchant","ailillSkill3Eff", stat=STRENGTH,power=200,trigger=TRIGGER_ON_REMOVE,lifeSteal=50,type=TYPE_DAMAGE,effPrio=1,emoji='<:ailillTwoStrikeRep:1044491016679460885>')
ailillSkill3 = skill("Frappe en deux-temps","ailillSkill3",TYPE_DAMAGE,power=ailillSkill3Eff.power,effects=ailillSkill3Eff,cooldown=3,tpCac=True,range=AREA_CIRCLE_2,description='Ailill inflige des dégâts directs à une cible unique, puis inflige un second coup lors du début de son prochain tour',emoji='<:ailillTwoStrike:1044490984572076142>')
ailillSkill7Eff, ailillSkill7Eff2 = copy.deepcopy(vulne), copy.deepcopy(incurable)
ailillSkill7Eff.power, ailillSkill7Eff.turnInit, ailillSkill7Eff2.power, ailillSkill7Eff2.turnInit = 25, 3, 50, 3
ailillSkill7_1 = skill("Disparité","ailillSkill7",TYPE_DAMAGE,power=650,cooldown=6,emoji='<:ailillSkill1:1044487636561178646>',lifeSteal=35,accuracy=250,effects=[ailillSkill7Eff,ailillSkill7Eff2],description="Ailill inflige de lourd dégâts à une cible unique, vol une partie des dégâts infligés et augmente les dégâts subis ainsi que les soins reçus de la cible de respectivement **{0}%** et **{1}%** pendant 3 tours".format(ailillSkill7Eff.power,ailillSkill7Eff2.power))
ailillSkill7_c = effect("Cast - {replicaName}","ailillSkill7_c",turnInit=2,silent=True,replique=ailillSkill7_1)
ailillSkill7 = copy.deepcopy(ailillSkill7_1)
ailillSkill7.power, ailillSkill7.effectOnSelf, ailillSkill7.effects = 0, ailillSkill7_c, [None]

kitsuneWeapEff = effect("Kitsune originelle",'kitsunePassifEff', stat=CHARISMA,magie=10,charisma=10,emoji='<:kitsuWeapEff:935553855272407080>',turnInit=-1,description="En subissant des dégâts, esquivant une attaque ou infligeant des dégâts, Kitsune donne l'effet __Charmé (Ennemi)__ à l'entité attanquante ou attaquée",callOnTrigger=charming)
kitsuneWeap = weapon("Magie multi-élémentaire",'kitsuneWeap',RANGE_DIST,AREA_CIRCLE_4,35,99,ignoreAutoVerif=True,repetition=3,charisma=35,endurance=20,effectOnUse=charming,use=MAGIE,effects=kitsuneWeapEff,emoji='<:kitsuWeap:935553775500947486>',priority=WEAPON_PRIORITY_LOWEST)
kitsuneSkill1_1 = skill("Flammes originelles",'kitsuneSkill1',TYPE_DAMAGE,power=120,area=AREA_CONE_3,cooldown=3,use=MAGIE,emoji='<:fireKitsune:917670925904785408>',say="Et si je chauffais un peu l'ambiance ?")
kitsuneSkill1_2 = skill("Glace Originelle","kitsuneSkill1",TYPE_DAMAGE,power=160,area=AREA_LINE_3,cooldown=3,use=MAGIE,emoji='<:waterKitsune:917670866626707516>')
kitsuneSkill1_3 = skill("Vent Originel",'kitsuneSkill1',TYPE_DAMAGE,power=160,range=AREA_MONO,area=AREA_CIRCLE_2,use=MAGIE,cooldown=2,emoji='<:airKitsune:917670912646602823>',say="Oh vous voulez me voir de près ? J'ai de quoi vous satisfaire")
kitsuneSkill1_4 = skill("Roche Originel",'kitsuneSkill1',TYPE_DAMAGE,power=145,range=AREA_CIRCLE_2,area=AREA_CIRCLE_1,cooldown=2,use=MAGIE,emoji='<:earthKitsune:917670882586017792>')
kitsuneSkill1 = skill("Magie Originelle",'kitsuneSkill1',TYPE_DAMAGE,become=[kitsuneSkill1_1,kitsuneSkill1_2,kitsuneSkill1_3,kitsuneSkill1_4],use=MAGIE)

kitsunedDot = effect("Saignement","kitsuneBleed", stat=MAGIE,power=50,turnInit=5,emoji='<:bleed:1083761078770618460>',trigger=TRIGGER_END_OF_TURN,type=TYPE_INDIRECT_DAMAGE)
kitsuneSkill2_1 = skill("Vent d'amour",'kitsuneSkill2',TYPE_MALUS,range=AREA_MONO,area=AREA_CIRCLE_2,emoji='<:verAero2:1042350921281191977>',effects=charming,effPowerPurcent=300,effectOnSelf=charming2,cooldown=3,say="Vous voulez vraiment rester aussi près ? Téméraires dites donc ^^",effectAroundCaster=[TYPE_INDIRECT_DAMAGE,AREA_CIRCLE_2,kitsunedDot])
kitsuneSkill2_2 = skill("Terre d'amour",'kitsuneSkill2',TYPE_MALUS,range=AREA_CIRCLE_2,area=AREA_CIRCLE_1,effects=charming,emoji='<:stone2:1053730589049618462>',effPowerPurcent=500,effectOnSelf=charming2,cooldown=3,effectAroundCaster=[TYPE_INDIRECT_DAMAGE,AREA_CIRCLE_2,kitsunedDot])
kitsuneSkill2_3 = skill("Feu d'amour",'kitsuneSkill2',TYPE_MALUS,range=AREA_MONO,area=AREA_DIST_5,effects=charming,effPowerPurcent=100,emoji='<:fireplace:931666078092902471>',effectOnSelf=charming2,cooldown=3,say="Vous voulez pas avoir une meilleure vue ? J'ai de quoi tous vous contenter vous savez ?",effectAroundCaster=[TYPE_INDIRECT_DAMAGE,AREA_DIST_5,kitsunedDot])
kitsuneSkill2_4 = skill("Eau d'amour",'kitsuneSkill2',TYPE_MALUS,range=AREA_DIST_5,area=AREA_CONE_3,effects=charming,effPowerPurcent=100,emoji='<:water2:1065647727708483654>',effectOnSelf=charming2,cooldown=3,effectAroundCaster=[TYPE_INDIRECT_DAMAGE,AREA_DIST_5,kitsunedDot])
kitsuneSkill2 = skill("Amour élémentaire",'kitsuneSkill2',TYPE_DAMAGE,become=[kitsuneSkill2_1,kitsuneSkill2_2,kitsuneSkill2_3,kitsuneSkill2_4],emoji='<:serenade:1047386802517971014>',use=CHARISMA,description="Kitsune charme les adversaires dans diverses zones d'effet et leur inflige des dégâts continus")

kitsuneSkill3_1 = skill("Vitesse aérienne",'kitsuneSkill3',TYPE_DAMAGE,power=100,range=AREA_INLINE_3,use=MAGIE,replay=True,cooldown=2,emoji='<:liaSkill:922291249002709062>',knockback=3,jumpBack=2)
kitsuneSkill3_2 = skill("Sable mouvants",'kitsuneSkill3',TYPE_DAMAGE,power=150,range=AREA_MONO,area=AREA_CIRCLE_2,use=MAGIE,cooldown=4,effectOnSelf=liuSkillEff,emoji=liuSkill.emoji)
kitsuneSkill3_3 = skill("Flamme infernales",'kitsuneSkill3',TYPE_INDIRECT_DAMAGE,range=AREA_MONO,area=AREA_ALL_ENEMIES,use=MAGIE,cooldown=3,emoji=lieSkill.emoji,effects=lizSkillSusEff)
kitsuneSKill3_4Eff = effect("Régénération",'kitsuneSkill3_4Eff', stat=CHARISMA,power=85,turnInit=3,lvl=3,emoji='<:lioWeap:908859876812415036>',type=TYPE_INDIRECT_HEAL,trigger=TRIGGER_START_OF_TURN)
kitsuneSkill3_4 = skill("Pluie infernale",'kitsuneSkill3',TYPE_DAMAGE,power=60,range=AREA_MONO,area=AREA_ALL_ENEMIES,use=MAGIE,cooldown=5,emoji=lioRez.emoji,setAoEDamage=True,effectOnSelf=kitsuneSKill3_4Eff)
kitsuneSkill3 = skill("Magie multi-élémentaire II",'kitsuneSkill3',TYPE_DAMAGE,become=[kitsuneSkill3_1,kitsuneSkill3_2,kitsuneSkill3_3,kitsuneSkill3_4],use=MAGIE)

kitsuneSkill4_1_eff = effect("Feu des volcans","With all the strength of a raging fire", stat=MAGIE,power=40,turnInit=3,lvl=3,trigger=TRIGGER_START_OF_TURN,emoji='<:enemyFire:1042312985407930428>',type=TYPE_INDIRECT_DAMAGE)
kitsuneSkill4_1_c = effect("Être plus ardent que le feu des volcans","volcanosReady",turnInit=3,silent=True,emoji='<:fire3:1042349767411376148>')
kitsuneSkill4_1 = skill("Feu des volcans","be a man",TYPE_DAMAGE,power=70,cooldown=5,use=MAGIE,setAoEDamage=True,range=AREA_MONO,area=AREA_ALL_ENEMIES,description="Kitsune inflige des dégâts à tous les ennemis et leur inflige un effet de dégâts sur la durée",effectAroundCaster=[TYPE_INDIRECT_DAMAGE,AREA_ALL_ENEMIES,kitsuneSkill4_1_eff],emoji="<:fire3:1042349767411376148>",needEffect=[kitsuneSkill4_1_c])
kitsuneSkill4_2_c = effect("Être plus puissant que les ouragans","tyfood",turnInit=3,emoji='<:verAero3:1042350960321769503>',silent=True)
kitsuneSkill4_2 = skill("Ouragans","be a man",TYPE_DAMAGE,power=160,cooldown=5,use=MAGIE,range=AREA_MONO,area=AREA_CIRCLE_4,description="Kitsune attire les ennemis autour d'elle et leur inflige des dégâts",pull=5,emoji="<:verAero3:1042350960321769503>",needEffect=[kitsuneSkill4_2_c],effectOnSelf=kitsuneSkill4_1_c)
kitsuneSkill4_3 = skill("Cours du Tourrant","be a man",TYPE_DAMAGE,power=150,cooldown=5,use=MAGIE,range=AREA_MONO,area=AREA_CIRCLE_3,description="Kitsune inflige des dégâts aux ennemis autour d'elle et les repousses",knockback=2,emoji="<:water3:1065647689129271397>",effectOnSelf=kitsuneSkill4_2_c)
kitsuneSkill4 = skill("Lune de l'Orient","be a man",TYPE_DAMAGE,become=[kitsuneSkill4_3,kitsuneSkill4_2,kitsuneSkill4_1],use=MAGIE,description="Kitsune inflige des dégâts aux ennemis autour d'elle et leur inflige des effets secondaires à l'aide de 3 compétences",emoji='<:enemyWater:1042313114487636038>')

naciaWeap = weapon("Lame Pangéenne","noneWeap",RANGE_DIST,AREA_CIRCLE_1,200,100,ignoreAutoVerif=True)
naciaEarthShield = effect("Armure Terrestre","naciaEarthShield",PURCENTAGE,overhealth=2.5,turnInit=4,stackable=True,emoji=liuAoEShieldEff.emoji,trigger=TRIGGER_DAMAGE,type=TYPE_ARMOR)
naciaFireEffTrigger1, naciaFireEffTrigger2 = effect("Aura Brûlante","naciaFireEffTrigger",MAGIE,power=35,area=AREA_DONUT_2,trigger=TRIGGER_INSTANT,type=TYPE_INDIRECT_DAMAGE,emoji=fireCircle.emoji), effect("Aura Brûlante","naciaFireEffTrigger",MAGIE,power=50,area=AREA_DONUT_4,trigger=TRIGGER_INSTANT,type=TYPE_INDIRECT_DAMAGE,emoji=fireCircle.emoji)
naciaWaterEffTrigger = effect("Régénération","naciaWaterEffTrigger",MISSING_HP,power=5/4,trigger=TRIGGER_INSTANT,emoji='<:enemyWater:1042313114487636038>',type=TYPE_INDIRECT_HEAL)
naciaAirWeakness2, naciaAirWeakness1 = copy.deepcopy(bonkWeakness), copy.deepcopy(bonkWeakness)
naciaAirWeakness2.power, naciaAirWeakness2.stackable, naciaAirWeakness2.silentRemove = 50, True, True
naciaAirWeakness1.power, naciaAirWeakness1.stackable, naciaAirWeakness1.silentRemove = 35, True, True
naciaEarthEff, naciaAirEff1, naciaAirEff2, naciaFireEff1, naciaFireEff2, naciaWaterEff = effect("Phase Terrestre","naciaEarthEff",turnInit=4,silent=True,emoji=elemEmojis[ELEMENT_EARTH],trigger=TRIGGER_END_OF_TURN,callOnTrigger=naciaEarthShield), effect("Phase Aérienne","naciaAirEff",turnInit=4,silent=True,emoji=elemEmojis[ELEMENT_AIR],callOnTrigger=naciaAirWeakness2,area=AREA_DONUT_2,trigger=TRIGGER_START_OF_TURN), effect("Phase Aérienne","naciaAirEff",turnInit=4,silent=True,emoji=elemEmojis[ELEMENT_AIR],callOnTrigger=naciaAirWeakness2,area=AREA_DONUT_5,trigger=TRIGGER_START_OF_TURN), effect("Phase Pyrotechnique","naciaFireEff",turnInit=4,silent=True,emoji=elemEmojis[ELEMENT_FIRE],trigger=TRIGGER_END_OF_TURN,callOnTrigger=naciaFireEffTrigger1), effect("Phase Pyrotechnique","naciaFireEff",turnInit=4,silent=True,emoji=elemEmojis[ELEMENT_FIRE],trigger=TRIGGER_END_OF_TURN,callOnTrigger=naciaFireEffTrigger2), effect("Phase Aquatique","naciaWaterEff",turnInit=4,silent=True,emoji=elemEmojis[ELEMENT_WATER],callOnTrigger=naciaWaterEffTrigger,trigger=TRIGGER_END_OF_TURN)
naciaSplashIconPulls = {naciaEarthEff.id: ['<:earthNacia:1208074102569566209>','<:earthGtsNacia:1208132160285048892>'], naciaAirEff1.id: ["<:airNacia:1208074166297952278>","<:airGtsNacia:1208132179616596009>"],naciaFireEff1.id: ["<:fireNacia:1208074195888504902>","<:fireGtsNacia:1208132209589100605>"], naciaWaterEff.id: ["<:waterNacia:1208074216973410405>","<:waterGtsNacia:1208132232599052308>"]}
naciaElemEffIds = naciaSplashIconPulls.keys()

GIANTESSHPBONUS, GIANTESSSTATBONUS = 75, 40

naciaSays = says(
    start="Doonc, pour résumer, vous vous êtes dit que vous pourrez me tenir tête avec genre, seulement seize personne ?",
    onKill=["Ah bah tout de même !","Eeeet donc ? C'était quoi le plan ?","C'était à prévoir non ?","Tu t'y attendais non ?","Et bah reste par terre !"],
    redWinAlive="J'avoue que je vois pas vraiment ce que vous aviez en tête",
    redLoose="Ok pouce ! Temps Mort ! Pourquoi on fais ça enfaite ? Vous avez clairement pas la puissance nécessaire pour tuer une déesse, donc c'est quoi la suite ?",
    reactEnemyLb="Waw c'est beau. Tu as fini maintenant ?",
    onHit=["Hé bah, prendre une attaque comme ça c'est pas donné à tout le monde","Il t'en faut encore sérieusement ?","Un jour il faudra apprendre à lacher l'affaire","Hurf","Tss.","Humf !"],
    takeHit=["Humf.","Et donc ?","`Soupire`","Très bien très bien, si tu insiste","Eh bah...","Hé, si je vous ai fait plus grand que des moustiques c'est pour que vous puissez faire plus mal que des moustiques","Hmmhmhm 🎵","Huh ?"]
)

giantessEff = effect("Puissance originelle","giantessNacialisla",emoji='<:naciaGiantEff:1052323849288568975>')
naciaGiantEff = effect("Puissance originelle","giantess",type=TYPE_UNIQUE,emoji='<:naciaGiant:1052323784562049185>',description="Augmente de **{0}%** les PV max et actuels de Nacialisla ainsi de **{1}%** sa Force, son Endurance, sa Précision et sa Magie, mais réduit de 100% sa probabilité d'esquive une attaque".format(GIANTESSHPBONUS,GIANTESSSTATBONUS),turnInit=6,trigger=TRIGGER_ON_REMOVE)
naciaDash = skill("Dash","naciaGiant",TYPE_DAMAGE,power=35,tpCac=True,rejectEffect=giantessEff,replay=True,range=AREA_DIST_3,cooldown=3,description="Nacialisla dash sur l'ennemi ciblé, lui inflige des dégâts et peut rejouer son tour. Cette compétence n'est plus utilisable une fois que Nacialisla a pris sa forme gigantesque")
naciaGiant = skill("Gigantification","naciaGiant",TYPE_PASSIVE,effects=naciaGiantEff,become=[naciaDash],description="Lorsque Nacialisla tombe en dessous de **60%** de ses PV maximums, cette dernière prend une forme gigantesque, augmentant toutes ses statistiques",emoji='<:naciaGiant:1052323784562049185>')
naciaGiant.initCooldown = 0
naciaGiantShockWave = effect("Onde de choc","naciaGiatessChocWave",MAGIE,power=50,area=AREA_ALL_ENEMIES,type=TYPE_INDIRECT_DAMAGE,trigger=TRIGGER_INSTANT,emoji='<:darkShockWave:1185653578824679484>', knockback=1)

naciaSkill1_1d = effect("Rechargement: Terre","naciaSkill11d",silent=True,type=TYPE_MALUS,turnInit=naciaEarthEff.turnInit*3,emoji='<:unepidemic:1016788322246471801>')
naciaSkill1_11 = skill("Frappe Sismique","naciaSkill1",TYPE_DAMAGE, range=AREA_MONO, area=AREA_CIRCLE_2, power=100, cooldown=4, effectOnSelf=naciaEarthEff, rejectEffect=[giantessEff, naciaSkill1_1d], damageOnArmor=2, description="Nacialisla inflige des dégâts aux ennemis alentours et rentre en {0}. De plus, en fin de tour, elle octient une armure en fonction de ses PV maximums".format(naciaEarthEff),emoji='<:smallEarthStrike:1208847304543571998>',effectAroundCaster=[TYPE_MALUS,AREA_MONO,naciaSkill1_1d])
naciaSkill1_12 = skill("Frappe Séismique",naciaSkill1_11.id,TYPE_DAMAGE, range=AREA_MONO, area=AREA_CIRCLE_3, power=150, cooldown=4, effectOnSelf=naciaEarthEff, rejectEffect=[naciaSkill1_1d], needEffect=giantessEff, damageOnArmor=2, description="Nacialisla inflige des dégâts aux ennemis alentours et rentre en {0}. De plus, en fin de tour, elle octient une armure en fonction de ses PV maximums".format(naciaEarthEff),emoji='<:earthStrike:1208837848392802376>',consumeNeededEffects=False,effectAroundCaster=[TYPE_MALUS,AREA_MONO,naciaSkill1_1d])
naciaSkill1_2d = effect("Rechargement: Air","naciaSkill12d",silent=True,type=TYPE_MALUS,turnInit=naciaEarthEff.turnInit*3,emoji='<:unepidemic:1016788322246471801>')
naciaSkill1_21 = skill("Frappe Aérienne",naciaSkill1_11.id,TYPE_DAMAGE, range=AREA_MONO, area=AREA_CIRCLE_2, power=100, cooldown=4, effectOnSelf=naciaAirEff1, rejectEffect=[giantessEff, naciaSkill1_2d], knockback=1, description="Nacialisla inflige des dégâts aux ennemis alentours, les repousse d'une case et rentre en {0}. De plus, au début de ses prochaines tours, augmente de **{1}%** les dégâts de colissions reçus par les ennemis proche de Nacialisla".format(naciaAirEff1,naciaAirWeakness1.power),emoji='<:smallAirStrike:1208847284931133522>',effectAroundCaster=[TYPE_MALUS,AREA_MONO,naciaSkill1_2d])
naciaSkill1_22 = skill("Frappe Tempête",naciaSkill1_11.id,TYPE_DAMAGE, range=AREA_MONO, area=AREA_CIRCLE_3, power=150, cooldown=4, effectOnSelf=naciaAirEff2, rejectEffect=[naciaSkill1_2d], needEffect=giantessEff, knockback=2, description="Nacialisla inflige des dégâts aux ennemis alentours, les repousse de deux cases et rentre en {0}. De plus, au début de ses prochaines tours, augmente de **{1}%** les dégâts de colissions reçus par les ennemis autour de Nacialisla".format(naciaAirEff1,naciaAirWeakness2.power),emoji='<:airStrike:1208802025840582698>',consumeNeededEffects=False,effectAroundCaster=[TYPE_MALUS,AREA_MONO,naciaSkill1_2d])
naciaSkill1_3d = effect("Rechargement: Eau","naciaSkill13d",silent=True,type=TYPE_MALUS,turnInit=naciaEarthEff.turnInit*3,emoji='<:unepidemic:1016788322246471801>')
naciaSkill1_31 = skill("Frappe Aquatique",naciaSkill1_11.id,TYPE_DAMAGE, range=AREA_MONO,use=MAGIE, area=AREA_DIST_4, power=100, cooldown=4, effectOnSelf=naciaWaterEff, rejectEffect=[giantessEff, naciaSkill1_3d], lifeSteal=5, description="Nacialisla inflige des dégâts éloignés en se soignant en fonction des dégâts infligés et rentre en {0}. De plus, en fin de tour, elle se soigne en fonction de ses PV manquants".format(naciaWaterEff),emoji='<:smallWaterStrike:1208847264592691291>',effectAroundCaster=[TYPE_MALUS,AREA_MONO,naciaSkill1_3d])
naciaSkill1_32 = skill("Frappe Tsunamique",naciaSkill1_11.id,TYPE_DAMAGE, range=AREA_MONO, use=MAGIE, area=AREA_DIST_7, power=150, cooldown=4, effectOnSelf=naciaWaterEff, rejectEffect=[naciaSkill1_3d], needEffect=giantessEff, lifeSteal=5, description="Nacialisla inflige des dégâts éloignés en se soignant en fonction des dégâts infligés et rentre en {0}. De plus, en fin de tour, elle se soigne en fonction de ses PV manquants".format(naciaWaterEff),emoji='<:waterStrike:1208840237426671749>',consumeNeededEffects=False,effectAroundCaster=[TYPE_MALUS,AREA_MONO,naciaSkill1_3d])
naciaSkill1_4d = effect("Rechargement: Feu","naciaSkill14d",silent=True,type=TYPE_MALUS,turnInit=naciaEarthEff.turnInit*3,emoji='<:unepidemic:1016788322246471801>')
naciaSkill1_41 = skill("Frappe Pyrotechnique",naciaSkill1_11.id,TYPE_DAMAGE, use=MAGIE, range=AREA_MONO, area=AREA_DIST_4, power=125, cooldown=4, effectOnSelf=naciaFireEff1, rejectEffect=[giantessEff, naciaSkill1_4d], description="Nacialisla inflige des dégâts éloignés et rentre en {0}. De plus, en fin de tour, elle inflige des dégâts indirects aux ennemis autour d'elle".format(naciaFireEff1),emoji='<:smallFireStrike:1208847240878227566>',effectAroundCaster=[TYPE_MALUS,AREA_MONO,naciaSkill1_4d])
naciaSkill1_42 = skill("Frappe Déflagrante",naciaSkill1_11.id,TYPE_DAMAGE, use=MAGIE, range=AREA_MONO, area=AREA_DIST_7, power=155, cooldown=4, effectOnSelf=naciaFireEff2, rejectEffect=[naciaSkill1_4d], needEffect=giantessEff, description="Nacialisla inflige des dégâts et rentre en {0}. De plus, en fin de tour, elle inflige des dégâts indirects aux ennemis autour d'elle".format(naciaFireEff2),emoji='<:fireStrike:1208789146554867742>',consumeNeededEffects=False,effectAroundCaster=[TYPE_MALUS,AREA_MONO,naciaSkill1_4d])

naciaSkill1 = skill("Frappe élémentaire",naciaSkill1_11.id,TYPE_DAMAGE,emoji='<:nacialislaSkill:1208854730227581000>',become=[naciaSkill1_11,naciaSkill1_12,naciaSkill1_21,naciaSkill1_22,naciaSkill1_31,naciaSkill1_32,naciaSkill1_41,naciaSkill1_42])

naciaSkill2_11 = skill("Lame Terrestre","naciaSkill2",TYPE_DAMAGE,range=AREA_CIRCLE_3, power=350, damageOnArmor=2, armorConvert=20,cooldown=4,emoji='<:earthLame:1208760037380718602>',rejectEffect=giantessEff,needEffect=[naciaEarthEff],consumeNeededEffects=False,description="Nacialisla inflige de fort dégâts à l'ennemi ciblé, augmentés contre l'armure, et obtient une armure en fonction des dégâts infligés")
naciaSkill2_12 = skill("Lame Pangéenne","naciaSkill2",TYPE_DAMAGE,range=AREA_CIRCLE_4, area=AREA_CIRCLE_1,power=1000, damageOnArmor=2, armorConvert=10,cooldown=4,emoji='<:rockLame:1208760088463155240>',needEffect=[naciaEarthEff, giantessEff],consumeNeededEffects=False,sharedTB=True,garCrit=True,description="Sous sa forme géante, Nacialisla inflige de fort dégâts aux ennemis ciblés. Les dégâts sont partagés en fonction du nombre de cibles, augmentés contre l'armure, et obtient une armure en fonction des dégâts infligés")
naciaSkill2_21 = skill("Lame Tempette","naciaSkill2",TYPE_DAMAGE,range=AREA_CIRCLE_3, power=125, repetition=3 ,cooldown=4,emoji='<:airArrow:980172706504908841>',needEffect=[naciaAirEff1],rejectEffect=giantessEff,consumeNeededEffects=False,description="Nacialisla inflige de fort dégâts à l'ennemi ciblé, à plusieurs reprises")
naciaSkill2_22 = skill("Lame Ouragant","naciaSkill2",TYPE_DAMAGE,range=AREA_CIRCLE_4, area=AREA_CIRCLE_2, power=200, repetition=3 ,cooldown=4,emoji='<:airArrow:980172706504908841>',needEffect=[naciaAirEff2, giantessEff],consumeNeededEffects=False,sharedTB=True,garCrit=True,description="Sous sa forme géante, Nacialisla inflige de fort dégâts aux ennemis ciblés à plusieurs reprises. Les dégâts sont partagés en fonction du nombre de cibles")
naciaSkill2_31 = skill("Lame Calcinante","naciaSkill2",TYPE_DAMAGE,range=AREA_DIST_4, power=200, area=AREA_CIRCLE_1 ,cooldown=4,emoji='<:firelame2:1156452806652330024>',needEffect=[naciaFireEff1],rejectEffect=giantessEff,consumeNeededEffects=False, sharedDamage=True, use=MAGIE,description="Nacialisla inflige des dégâts aux ennemis ciblés. Les dégâts sont partagés en fonction du nombre de cibles dans la zone d'effet")
naciaSkill2_32 = skill("Pluie de Lave","naciaSkill2",TYPE_DAMAGE,range=AREA_DIST_5, area=AREA_CIRCLE_4, power=900,cooldown=4,emoji='<:lavaRain:1208833711873859698>',needEffect=[naciaFireEff2, giantessEff],consumeNeededEffects=False, sharedDamage=True, use=MAGIE,description="Sous sa forme géante, Nacialisla inflige des dégâts dans une énorme zone. Les dégâts sont partégés en fonction du nombre de cibles dans la zone d'effet")
naciaSkill2_41 = skill("Lame Aquatique","naciaSkill2",TYPE_DAMAGE,range=AREA_DIST_4, power=300, area=AREA_CIRCLE_3, cooldown=4, lifeSteal=5,emoji='<:icelame2:1156452836964569148>',needEffect=[naciaWaterEff],rejectEffect=giantessEff,consumeNeededEffects=False, sharedDamage=True, use=MAGIE, description="Nacialisla inflige des dégâts dans une énorme zone et se soigne en fonction des dégâts infligés. Les dégâts sont partégés en fonction du nombre de cibles dans la zone d'effet")
naciaSkill2_42 = skill("Grèle","naciaSkill2",TYPE_DAMAGE,range=AREA_DIST_5, area=AREA_ALL_ENEMIES, power=750, cooldown=4, lifeSteal=10,emoji='<:iceRain:1208833511193317447>',needEffect=[naciaWaterEff, giantessEff],consumeNeededEffects=False, sharedDamage=True, use=MAGIE, description="Nacialisla inflige des dégâts à tous les ennemis et se soigne en fonction des dégâts infligés. Les dégâts sont partégés en fonction du nombre de cibles dans la zone d'effet")

naciaSkill2 = skill("Lame élémentaire","naciaSkill2",TYPE_DAMAGE,emoji='<:nacialislaSkill:1208854730227581000>',become=[naciaSkill2_11,naciaSkill2_12,naciaSkill2_21,naciaSkill2_22,naciaSkill2_31,naciaSkill2_32,naciaSkill2_41,naciaSkill2_42])

naciaSkill3_11 = skill("Séisme","naciaSkill3",TYPE_DAMAGE,power=200,range=AREA_MONO,area=AREA_CIRCLE_2, damageOnArmor=2, armorConvert=10, needEffect=[naciaEarthEff],rejectEffect=giantessEff,cooldown=4,consumeNeededEffects=False, emoji='<:seisme:1208794883800830042>',description="Nacialisla inflige des dégâts aux ennemis autour d'elle en convertissant une partie des dégâts infligés en armure")
naciaSkill3_12 = skill("Piétinement Terrestre","naciaSkill3",TYPE_DAMAGE,power=1000,range=AREA_CIRCLE_1,area=AREA_CIRCLE_2, damageOnArmor=2, armorConvert=2.5, needEffect=[naciaEarthEff, giantessEff],cooldown=4,consumeNeededEffects=False,emoji='<:naciaStomp:1208777355750019162>',sharedDamage=True,garCrit=True,description="Sous sa forme géante, Nacialisla inflige de gros dégâts à un ennemi au corps à corps et ceux alentours. La cible principale reçoit forcément un coup critique et les dégâts sont partagés en fonction du nombre d'e combattant de mêlée dans' la zone d'effet")
naciaSkill3_21 = skill("Choc Aérien","naciaSkill3",TYPE_DAMAGE,power=200,range=AREA_MONO,area=AREA_CIRCLE_2, knockback=1, needEffect=[naciaAirEff1], rejectEffect=giantessEff,consumeNeededEffects=False, emoji='<:aerialChoc:1208802006769209396>',cooldown=4,description="Nacialisla inflige des dégâts aux ennemis autour d'elle et les repoussent de une case")
naciaSkill3_22 = skill("Piétinement Expulsif","naciaSkill3",TYPE_DAMAGE,power=1200,range=AREA_CIRCLE_1,area=AREA_CIRCLE_3, knockback=2, needEffect=[naciaAirEff2, giantessEff],consumeNeededEffects=False,emoji='<:arealStomp:1208827586306637854>',cooldown=4,sharedDamage=True,garCrit=True,description="Sous sa forme géante, Nacialisla inflige de gros dégâts à un ennemi au corps à corps et aux ennemis dans une large zone autour. Les dégâts sont partagés en fonction du nombre de cible dans la zone d'effet, et les ennemis sont repoussés de deux cases")
naciaSkill3_31e1 = effect("Combustion","naciaSkill31e1",MAGIE,type=TYPE_INDIRECT_DAMAGE,power=20,turnInit=3,trigger=TRIGGER_END_OF_TURN,emoji='<:enemyFire:1042312985407930428>')
naciaSkill3_32e1, naciaSkill3_31e = copy.deepcopy(naciaSkill3_31e1), effect("Souffle Enflammé","naciaSkill31e",type=TYPE_MALUS,area=AREA_CONE_3,callOnTrigger=naciaSkill3_31e1,emoji='<:fireBreath:1208793209728143400>',trigger=TRIGGER_INSTANT)
naciaSkill3_31 = skill("Souffle Enflammé","naciaSkill3",TYPE_DAMAGE,power=200,range=AREA_CIRCLE_1,use=MAGIE,effects=naciaSkill3_31e,area=naciaSkill3_31e.area,rejectEffect=giantessEff,emoji=naciaSkill3_31e.emoji[0][0],cooldown=4,needEffect=[naciaFireEff1],consumeNeededEffects=False,description="Nacialisla souffle un air brûlant sur un ennemi au corps à corps, lui infligeant des dégâts ainsi qu'aux ennemis derrnière. Les cibles affectés reçoivent des dégâts indirects pendant un petit moment")
naciaSkill3_32e1.power, naciaSkill3_32e = 40, effect("Souffle Calcinant","naciaSkill31e",type=TYPE_MALUS,area=AREA_CONE_5,callOnTrigger=naciaSkill3_32e1,emoji='<:flareBreath:1208793257497198593>',trigger=TRIGGER_INSTANT)
naciaSkill3_32 = skill("Souffle Calcinant","naciaSkill3",TYPE_DAMAGE,power=225,garCrit=True,range=AREA_CIRCLE_1,use=MAGIE,effects=naciaSkill3_32e,area=naciaSkill3_32e.area,emoji=naciaSkill3_32e.emoji[0][0],cooldown=4,needEffect=[naciaFireEff2, giantessEff],consumeNeededEffects=False,description="Sous sa forme géante, Nacialisla souffle un air bouillant sur un ennemi au corps à corps, lui infligeant des dégâts critique ainsi que des dégâts aux ennemis dans une large zone derrière. Les cibles affectés reçoivent des dégâts indirects pendant un petit moment")
naciaSkill3_41 = skill("Souffle Aquatique","naciaSkill3",TYPE_DAMAGE,power=250,range=AREA_CIRCLE_1,emoji='<:waterBreath:1208793235477102622>',use=MAGIE,area=naciaSkill3_31e.area,rejectEffect=giantessEff,cooldown=4,needEffect=[naciaWaterEff],consumeNeededEffects=False,description="Nacialisla souffle un air givrant sur un ennemi au corps à corps, lui infligeant des dégâts ainsi qu'aux ennemis derrnière et se soigne en fonction des dégâts infligés")
naciaSkill3_42 = skill("Souffle Torrentiel","naciaSkill3",TYPE_DAMAGE,power=285,garCrit=True,range=AREA_CIRCLE_1, emoji='<:riptideBreath:1208793284357525595>',use=MAGIE,area=naciaSkill3_32e.area,cooldown=4,needEffect=[naciaWaterEff, giantessEff],consumeNeededEffects=False,description="Sous sa forme géante, Nacialisla souffle un blisard sur un ennemi au corps à corps, lui infligeant des dégâts critique ainsi que des dégâts aux ennemis dans une large zone derrière et se soigne en fonction des dégâts infligés")

naciaSkill3 = skill("Souffle élémentaire","naciaSkill3",TYPE_DAMAGE,emoji='<:nacialislaSkill:1208854730227581000>',become=[naciaSkill3_11,naciaSkill3_12,naciaSkill3_21,naciaSkill3_22,naciaSkill3_31,naciaSkill3_32,naciaSkill3_41,naciaSkill3_42])

naciaSkill4_11 = skill("Pics Terrestres","naciaSkill4",TYPE_DAMAGE,range=AREA_MONO,area=AREA_CIRCLE_3,power=200,setAoEDamage=True,use=MAGIE,needEffect=[naciaEarthEff],rejectEffect=giantessEff,consumeNeededEffects=False,cooldown=4,damageOnArmor=3,emoji='<:rockSpike:1208778908632227882>',armorConvert=5,description="Nacialisla inflige des dégâts aux ennemis autour d'elle en ignorant la réduction de dégâts de zone et en convertissant une partie des dégâts infligés en armure")
naciaSkill4_12 = skill("Pics Pangéens","naciaSkill4",TYPE_DAMAGE,range=AREA_MONO,area=AREA_ALL_ENEMIES,power=100,setAoEDamage=True,use=MAGIE,needEffect=[naciaEarthEff,giantessEff],consumeNeededEffects=False,cooldown=4,damageOnArmor=3,emoji=rocklance.emoji,armorConvert=5,description="Sous sa forme géante, Nacialisla inflige des dégâts à tous ses ennemis en ignorant la réduction de dégâts de zone et en convertissant une partie des dégâts infligés en armure")
naciaSkill4_21 = skill("Zéphir","naciaSkill4",TYPE_DAMAGE,range=AREA_MONO,area=AREA_DIST_3,power=150,setAoEDamage=True,use=MAGIE,needEffect=[naciaAirEff1],rejectEffect=giantessEff,consumeNeededEffects=False,cooldown=4,emoji='<:catAir:956599718522265610>',description="Nacialisla inflige des dégâts dans une large zone, en ignorant la réduction de dégâts de zone et repoussant les ennemis touchés d'une case",knockback=1)
naciaSkill4_22 = skill("Ouragant","naciaSkill4",TYPE_DAMAGE,range=AREA_MONO,area=AREA_ALL_ENEMIES,power=100,setAoEDamage=True,use=MAGIE,needEffect=[naciaAirEff2,giantessEff],consumeNeededEffects=False,cooldown=4,emoji=storm.emoji,description="Sous sa forme géante, Nacialisla inflige des dégâts à tous ses ennemis, en ignorant la réduction de dégâts de zone et repousse les ennemis de deux cases",knockback=2)
naciaSkill4_31 = skill("Brasier","naciaSkill4",TYPE_DAMAGE,range=AREA_CIRCLE_2,area=AREA_CIRCLE_1,power=600,sharedTB=True,use=MAGIE,needEffect=[naciaFireEff1],rejectEffect=giantessEff,consumeNeededEffects=False,cooldown=4,emoji=fireCircle.emoji,description="Nacialisla inflige de gros dégâts de zone autour de l'ennemi ciblé. Les dégâts sont partagés en fonction du nombre de combattant de mêlée dans la zone d'effet")
naciaSkill4_32 = skill("Inferno","naciaSkill4",TYPE_DAMAGE,range=AREA_CIRCLE_4,area=AREA_CIRCLE_2,power=1000,sharedDamage=True,use=MAGIE,needEffect=[naciaFireEff2, giantessEff],consumeNeededEffects=False,cooldown=4,emoji='<:flamePillar:1208788881961656400>',description="Sous sa forme géante, Nacialisla invoque un énorme pillier de feu sous les ennemis cibles. Les dégâts sont partagés parmis toutes les cibles")
naciaSkill4_41 = skill("Stalactite","naciaSkill4",TYPE_DAMAGE,range=AREA_CIRCLE_2,power=500,garCrit=True,use=MAGIE,needEffect=[naciaWaterEff],rejectEffect=giantessEff,consumeNeededEffects=False,cooldown=4,emoji='<:stalactite:1208824573186015232>',description="Nacialisla inflige de gros dégâts monocibles à l'ennemi ciblé")
naciaSkill4_42 = skill("Iceberg","naciaSkill4",TYPE_DAMAGE,range=AREA_CIRCLE_4,area=AREA_CIRCLE_2,power=900,garCrit=True,sharedDamage=True,lifeSteal=5,use=MAGIE,needEffect=[naciaWaterEff, giantessEff],consumeNeededEffects=False,cooldown=4,emoji='<:iceberg:1208824598737723522>',description="Sous sa forme géante, Nacialisla fait tomber un iceberg sur l'ennemi ciblé, infligeant des dégâts partégés à toutes les cibles dans la zone d'effet, infligeant un coup critique à la cible principale et se soigne légèrement en fonction des dégâts infligés")

naciaSkill4 = skill("Magie élémentaire","naciaSkill4",TYPE_DAMAGE,emoji='<:nacialislaSkill:1208854730227581000>',become=[naciaSkill4_11,naciaSkill4_12,naciaSkill4_21,naciaSkill4_22,naciaSkill4_31,naciaSkill4_32,naciaSkill4_41,naciaSkill4_42])

naciaConds = {naciaEarthEff.id:ELEMENT_EARTH,naciaAirEff1.id:ELEMENT_AIR,naciaFireEff1.id:ELEMENT_FIRE,naciaWaterEff.id:ELEMENT_WATER}
tablNacia = [naciaSkill2,naciaSkill3,naciaSkill4]
for inx1 in range(len(tablNacia)):
    for inx2 in range(len(tablNacia[inx1].become)):
        tablNacia[inx1].become[inx2].condition = [EXCLUSIVE,ELEMENT,naciaConds[tablNacia[inx1].become[inx2].needEffect[0].id]]
        if len(tablNacia[inx1].become[inx2].needEffect) > 1 and tablNacia[inx1].become[inx2].needEffect[1].id == giantessEff.id:
            tablNacia[inx1].become[inx2].onArmor = tablNacia[inx1].become[inx2].onArmor * 1.25


iliOvlWeaponEff = effect("Contre","iliOvlWeaponEff",block=10,counterOnBlock=100,turnInit=-1,unclearable=True,emoji='<:iliOvlWeap:1139249680031699027>')
iliOvlWeapon = weapon("Rapière de Lumière","iliOvlWeapon",RANGE_DIST,AREA_CIRCLE_1,power=150,accuracy=80,emoji='<:iliOvlWeap:1139249680031699027>',effects=iliOvlWeaponEff,ignoreAutoVerif=True,priority=WEAPON_PRIORITY_LOWEST,use=MAGIE,damageOnArmor=2)
iliOvlSkill1 = skill("Perforation","iliOvlSkill1",TYPE_DAMAGE,power=350,range=AREA_CIRCLE_1,area=AREA_LINE_3,accuracy=200,emoji='<:iliOvlSkill1:1139249727012098229>',garCrit=True,cooldown=5,description="Iliana inflige une attaque transperçante aux ennemis ciblés. La cible initiale reçoit forcément un coup critique",use=MAGIE,damageOnArmor=1.25,condition=[EXCLUSIVE,ELEMENT,ELEMENT_LIGHT])
iliOvlSkill2_1 = skill("Rayon Diffractif","iliOvlSkill2",TYPE_DAMAGE,power=250,area=AREA_CONE_3,range=AREA_CIRCLE_1,cooldown=3,emoji='<:iliOvlSkill22:1139254745337438300>',description="Inflige une attaque en cône aux ennemis ciblés",use=MAGIE,damageOnArmor=1.25,condition=[EXCLUSIVE,ELEMENT,ELEMENT_LIGHT])
iliOvlSkill2_2 = skill("Rayon Concentré","iliOvlSkill2",TYPE_DAMAGE,power=350,area=AREA_CIRCLE_1,range=AREA_CIRCLE_1,cooldown=3,emoji='<:iliOvlSkill21:1139254767604990002>',description="Inflige une attaque en cercle aux ennemis ciblés",use=MAGIE,damageOnArmor=1.5,condition=[EXCLUSIVE,ELEMENT,ELEMENT_LIGHT])
iliOvlSkill2 = skill("Rayon de Lumière","iliOvlSkill2",TYPE_DAMAGE,become=[iliOvlSkill2_1,iliOvlSkill2_2],emoji='<:iliOvlSkill21:1139254767604990002>',description="Iliana inflige des dégâts de zone aux ennemis ciblés",condition=[EXCLUSIVE,ELEMENT,ELEMENT_LIGHT])
iliOvlSkill3 = skill("Vitesse Lumière","iliOvlSkill3",TYPE_DAMAGE,power=50,area=AREA_RANDOMENNEMI_5,range=AREA_MONO,repetition=3,emoji='<:iliOvlSkill3:1139249659701887027>',damageOnArmor=1.25,accuracy=200,setAoEDamage=True,cooldown=5,use=MAGIE,description="Inflige des dégâts à 15 reprises à des ennemis aléatoire",condition=[EXCLUSIVE,ELEMENT,ELEMENT_LIGHT])
iliOvlSkill4Eff1 = copy.deepcopy(vulne)
iliOvlSkill4Eff1.power, iliOvlSkill4Eff1.turnInit = 25,3
iliOvlSkill4 = skill("Corruption","iliSkill4",TYPE_DAMAGE,power=225,range=AREA_MONO,area=AREA_CIRCLE_3,cooldown=5,effectAroundCaster=[TYPE_MALUS,AREA_DONUT_3,iliOvlSkill4Eff1],emoji='<:iliOvlSkill4:1139249705570795690>',accuracy=200,use=MAGIE,description="Inflige des dégâts aux ennemis alentours et augmente les dégâts qu'ils subissent",damageOnArmor=1.25,condition=[EXCLUSIVE,ELEMENT,ELEMENT_LIGHT])
iliOvlSkill5 = skill("Révolution","iliSkill5",TYPE_DAMAGE,power=275,range=AREA_MONO,area=AREA_DIST_7,effectAroundCaster=[TYPE_DAMAGE,AREA_CIRCLE_2,150],use=MAGIE,initCooldown=2,cooldown=7,description="Inflige des dégâts aux ennemis éloignés, ainsi qu'une attaque plus puissante aux ennemis proches de vous",damageOnArmor=1.35,condition=[EXCLUSIVE,ELEMENT,ELEMENT_LIGHT],emoji='<:iliOvlSkill5:1139249633877557309>')
iliOvlSkill6Eff = copy.deepcopy(dmgUp)
iliOvlSkill6Eff.turnInit, iliOvlSkill6Eff.power, 5, 15
iliOvlSkill6 = skill("Oblation","iliOvlSkill6",TYPE_DAMAGE,power=180,area=AREA_CIRCLE_2,range=AREA_CIRCLE_3,effectOnSelf=iliOvlSkill6Eff,use=MAGIE,description="Inflige des dégâts aux ennemis ciblés et augmente vos dégâts infligés",initCooldown=2,cooldown=5,emoji='<:iliOvlSkill6:1139254326494244864>')

iliOvlSkill7Eff = effect("Jauge de Lumière","iliLightJauge",turnInit=-1,unclearable=True,emoji=elemEmojis[ELEMENT_LIGHT],jaugeValue=jaugeValue(
    emoji=jaugeButLight.jaugeValue.emoji,
    conds=[
        jaugeConds(INC_ALLY_DAMAGED,100/75/5)
    ]
))
iliOvlSkill7_1 = skill("Lumière de l'Éternité","iliOvlSkill7",TYPE_DAMAGE,power=500,range=AREA_MONO,setAoEDamage=True,cooldown=99,area=AREA_CIRCLE_2,emoji='<:ancientLight2:1147186259115118613>',ultimate=True,percing=5,description="Lorsque la {0} {1} d'Iliana est remplie, celle-ci inflige des dégâts en croix autour d'elle puis se met à charger Lumière de l'Éternité, infligeant d'énormes dégâts à tous ses ennemis".format(iliOvlSkill7Eff.emoji[0][0],iliOvlSkill7Eff.name),jaugeEff=iliOvlSkill7Eff,accuracy=500,effectAroundCaster=[TYPE_DAMAGE,AREA_DIST_7,175],use=MAGIE,minJaugeValue=100,say="ET MOURREZ !")
iliOvlSkill7_c = effect("Cast - Lumière de l'Éternité","iliOvlSkill7_c",turnInit=2,emoji='<:ancientLight1:1147186235727695943>',replique=iliOvlSkill7_1)
iliOvlSkill7 = skill("Lumière de l'Éternité","iliOvlSkill7",TYPE_DAMAGE,power=150,range=AREA_MONO,cooldown=99,area=AREA_INLINE_2,emoji='<:ancientLight1:1147186235727695943>',ultimate=True,description=iliOvlSkill7_1.description,effectOnSelf=iliOvlSkill7_c,jaugeEff=iliOvlSkill7Eff,minJaugeValue=100,use=MAGIE,say="MARCHEZ DANS LA LUMIÈRE !")
iliOvlSkill7.iaPow = 9999

importantSkills.append(iliOvlSkill6.id); importantSkills.append(iliOvlSkill4.id); importantSkills.append(iliOvlSkill3.id); importantSkills.append(iliOvlSkill7.id)

iliOvlSay= says(
    start="Vous pensez tenir combien de temps ?",
    onKill=["Un de moins !","Déjà ?","C'est tout ?","Moh, j'avais encore plein de trucs à te montrer"],
    redWinAlive="Vous pensiez avoir une chance ?",redWinDead="Tss. Trop lente",redLoose="Hmf... Ce que j'aimerais me cacher dans un coin là tout de suite...",
    blockBigAttack="C'est tout ce que tu peux faire ?",onHit=["Heh. On va bien voir combien de temps tu va pouvoir tenir","On encaisse bien manifestement","Pas trop mal","Oh je suppose que j'n'ai qu'à taper plus fort"],
    onMiss=["Huh","Hé tu pourrais arrêter de bouger deux secondes oui ?","Hmf"],takeHit=["Même un moustique a plus d'effet","Tu essayais vraiment là ?","Pas mal. À mon tour","Pas mal. J'peux commencer maintenant ?"])
